### ISSUE TITLE
Parsing is not done yet

### ISSUE THREAD

**Issue by ArminKuburas** [ArminKuburas/minishell#3]
I have not finished making the parser. That is a big step of the project and will most likely take a week or two to do. It will be important to finish it in a timely manner.

**Comment by Tuubeloid** [comment]
Thats okay, I'm sure you will be done with it on time. I will help the best I can.

**Comment by ArminKuburas** [comment]
A few steps of the parser have been done now. We properly split up the data given to us (so far at least from testing done by me) and now we also catch and create the data needed for the child process. Currently the only thing I catch is the command itself (if it exists) next step for tomorrow (if possible) is to create the argument list for the command as well.

**Comment by Tuubeloid** [comment]
Thanks for the update!

**Comment by ArminKuburas** [comment]
bananashell-0.07:>output<input l"s" -l|>output2<input2 ec"ho" what the frick"?"<different_input"?"
split_input[0] = >
split_input[1] = output
split_input[2] = <
split_input[3] = input
split_input[4] = l"s"
split_input[5] = -l
split_input[6] = |
split_input[7] = >
split_input[8] = output2
split_input[9] = <
split_input[10] = input2
split_input[11] = ec"ho"
split_input[12] = what
split_input[13] = the
split_input[14] = frick"?"
inside print loop
Command 1: l"s"
inside print loop
Command 2: ec"ho"

Here is an example of what it can handle at the moment. 

Next step will be to include a function that expands the quotes so that something like:
ec"ho" will become echo or that if we find $ symbols inside " " it will expand them properly.

**Comment by ArminKuburas** [comment]
Update:

Still working on this. It is certainly larger then initially enticipated but should be done this week (hopefully by today it should be in its most final stages) most issues handled.

**Comment by ArminKuburas** [comment]
parsing done
