### ISSUE TITLE
Not all rl functions working properly yet.

### ISSUE THREAD

**Issue by Tuubeloid** [ArminKuburas/minishell#4]
-Usage of rl_on_new_line(), rl_replace_line("", 0) and rl_redisplay() causes some implicit declaration crying so need to figure out what that is all about.

**Comment by ArminKuburas** [comment]
Try to declare them in the header file. Like prototype them in there and see if it works?

**Comment by ArminKuburas** [comment]
Otherwise we can go and ask some of the other students who are further again with the project for their opinion
