### ISSUE TITLE
Signal handling still incomplete

### ISSUE THREAD

**Issue by Tuubeloid** [ArminKuburas/minishell#5]
Got rid of the ^C on the prompt when on default mode, still need to implement some kind of switching function that handles the few cases where ^C actually should be displayed for example "when in bash and you have inputted cat for example, then you CTRL+C the ^C will display without prompt. "

**Comment by ArminKuburas** [comment]
Okay will have you try this out in school. Thanks for the update!

**Comment by ArminKuburas** [comment]
signal handling done
