### ISSUE TITLE
We should make the env variables into a linked list but I think I'd rather do that next week with Taneli as it would be something that would affect his built-ins

### ISSUE THREAD

**Issue by ArminKuburas** [ArminKuburas/minishell#7]
So yeah as the title states. We would profit greatly from having a linked list. It would be much easier to add new elements into it with functions like export which is a built-in. Anyway next week might include a lot of us working together. It would be a nice milestone to have if we could easily pull our two branches into the main either tomorrow or next week.

**Comment by Tuubeloid** [comment]
Yeah sounds good to me! Linked lists rock. Lets try out the merging tomorrow, I think we can use the whole day for it if needed.

**Comment by ArminKuburas** [comment]
Okay this has been done. As well as inputs being inside separate linked lists. Issue resolved. A much needed improvement as well.
